### ISSUE TITLE
No such file or directory: 'data/LES-AV/images'

### ISSUE THREAD

**Issue by getcontrol** [agaldran/lwnet#2]
`No such file or directory: 'data/LES-AV/images' `after running `get_public_data.py`

Everything else seemed to download correctly to data/

**Comment by agaldran** [comment]
Hi @getcontrol 

Apparently the owner of the LES-AV data has moved it from its previous host to figshare. You can download it directly from here:

https://figshare.com/articles/dataset/LES-AV_dataset/11857698

And then once you have the zip file apply the same instructions you can find in `get_public_data.py`. I will try and fix the automatic download one of these days.
