### ISSUE TITLE
a few questions about label/target 

### ISSUE THREAD

**Issue by waibi8bo** [agaldran/lwnet#7]
1\
in get_loaders.py ,line 44:
target = self.label_encoding(target)
target = np.array(self.label_encoding(target))

why label_encoding run twice?

2\
I build my own dataset like manual_av in DRIVE,
but why my manual_av.png has the gray degree as 0, 29, 76, 150 instead of 0, 85, 170, 255 after using "convert('L')"?
So I have to set label_values=[0, 150, 76, 29 ] not label_values=[0, 85, 170, 255].

THANK YOU!!!

**Comment by agaldran** [comment]
Hi @waibi8bo 

You are absolutely right, that was a typo, label encoding should only be applied once, I will correct it. The second question, I do not understand well what you mean. In theory when you run get_public_data, [these lines](https://github.com/agaldran/lwnet/blob/1c622a4dbbcd97a83087fee3e58403f9c1a516b9/get_public_data.py#L133) convert RGB to grayscale with values [0, 85, 170, 255]. Do you mean that when you take one of those images `x.png` and do `Image.open(x).convert('L')`, you get an image with values 0, 29, 76, 150? That would be quite surprising, if that is the case please let me know and I will check.

Adrian

**Comment by waibi8bo** [comment]
I found a formule (g = 0.299*R + 0.578* G +0.114* B) in the Internet, which may cause the values 0, 29, 76, 150, but I have no idea what difference between my manual.png and DRIVE . 

I just combine my artery and vein segmentation simply using the code below to a RGB png like an img in DRIVE_av.

>     image = cv.imread(image_path,1)
>     manuala = cv.imread(manuala_path,0)
>     reta,manuala = cv.threshold(manuala,50,255,cv.THRESH_BINARY)
>     manualv = cv.imread(manualv_path,0)
>     retv,manualv = cv.threshold(manualv,50,255,cv.THRESH_BINARY)
>     manual = np.zeros(image.shape)
>     w,h = manuala.shape
>     for i in range(w):
>         for j in range(h):
>             pixela = manuala[i,j]
>             pixelv = manualv[i,j]
>             if pixela == 0 and pixelv==0:
>                 manual[i,j,0] = 0
>                 manual[i,j,1] = 0
>                 manual[i,j,2] = 0
>             elif pixela == 255 and pixelv==0:
>                 manual[i,j,0] = 0
>                 manual[i,j,1] = 0
>                 manual[i,j,2] = 255
>             elif pixela == 0 and pixelv==255:
>                 manual[i,j,0] = 255
>                 manual[i,j,1] = 0
>                 manual[i,j,2] = 0
>             elif pixela == 255 and pixelv==255:
>                 manual[i,j,0] = 0
>                 manual[i,j,1] = 255
>                 manual[i,j,2] = 0
>             else:
>                 print('error')

I guess it may be a silly and simple problem...

THANK U AGAIN !
